idf_component_register(
    SRCS "ui_assets.c" "generated_font_metadata.c"
    INCLUDE_DIRS "include"
    REQUIRES renderer
    EMBED_FILES
        "generated_page_pc.rgb565"
        "generated_page_codex.rgb565"
        "generated_wifi_up.rgba565"
        "generated_wifi_down.rgba565"
        "generated_weather_m00.rgba565"
        "generated_weather_m01.rgba565"
        "generated_weather_m02.rgba565"
        "generated_weather_m03.rgba565"
        "generated_weather_m04.rgba565"
        "generated_weather_m05.rgba565"
        "generated_weather_m06.rgba565"
        "generated_weather_m07.rgba565"
        "generated_weather_m08.rgba565"
        "generated_weather_m09.rgba565"
        "generated_weather_m10.rgba565"
        "generated_weather_m11.rgba565"
        "generated_weather_m12.rgba565"
        "generated_weather_m13.rgba565"
        "generated_weather_m14.rgba565"
        "generated_weather_m15.rgba565"
        "generated_weather_m16.rgba565"
        "generated_weather_m17.rgba565"
        "generated_weather_m18.rgba565"
        "generated_weather_m19.rgba565"
        "generated_weather_m20.rgba565"
        "generated_weather_m21.rgba565"
        "generated_weather_m22.rgba565"
        "generated_weather_m23.rgba565"
        "generated_weather_m24.rgba565"
        "generated_weather_m25.rgba565"
        "generated_weather_m26.rgba565"
        "generated_font_20.bin"
        "generated_font_24.bin"
        "generated_font_56.bin"
)
